version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:13.7.0-stretch-browsers
    steps:

      - restore_cache:
          keys:
            - v1-bozon-git

      - checkout

      - save_cache:
          paths:
            - ~/bozon/.git
          # Yes, the key is constant, meaning we'll have just one git cache
          # and pull the delta every time. That still saves a lot of clone time.
          # DON'T make a new cache for each revision!
          key: v1-bozon-git

      - restore_cache:
          keys:
            - v1-bozon-yarn-{{ arch }}-{{ .Branch }}
            - v1-bozon-yarn-{{ arch }}-master

      - run:
          name: Install Javascript dependencies
          command: |
            yarn install

      - run:
          name: Verify that committed yarn.lock is up to date
          command: |
            git diff-index --exit-code --quiet HEAD -- yarn.lock || { echo 'Run yarn and commit changes to yarn.lock!'; false; }

      - run:
          name: Test Javascript
          command: yarn test

      - store_test_results:
          path: spec/reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
